# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
#rdiscount:
#  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://root-master.github.io/
hosturl: http://root-master.github.io/
baseurl: http://root-master.github.io/
title: Jacob Rafati
author: Jacob Rafati
description: Academic and Professional website
avatar: profile.jpg
email: jrafatiheravi@ucmerced.edu
github: root-master # username
instagram: rmanakb
linkedin: jacob-rafati-22494785
work: University of California, Merced.

#include: ['_pages']
# needed for travis-ci build
exclude: [vendor]
include: ['_pages']
